name: "Docker build, tag and push"
description: "Creates a docker image for a target using the provided Dockerfile caches locally, and optionally pushes to the registry."
inputs:
  image-name:
    description: "The name of the image to build."
    required: true
  target:
    description: "The name of the image layer to build."
    required: false
  aws-access-key:
    description: "AWS Access key used for pushing to the registry"
    required: false
  aws-access-secret:
    description: "AWS Access secret used for pushing to the registry"
    required: false
  aws-region:
    description: "AWS region for the ECR registry"
    required: false
  cache-from:
    description: "List of external cache sources (e.g., type=local,src=path/to/dir)"
    required: false
  cache-to:
    description: "List of cache export destinations (e.g., type=local,dest=path/to/dir)"
    required: false
runs:
  using: "composite"
  steps:
    - name: Check if AWS login and push is required
      id: aws-login
      uses: haya14busa/action-cond@v1
      with:
        cond: ${{ inputs.aws-access-key != '' && inputs.aws-access-secret != '' && inputs.aws-region != '' }}
        if_true: true
        if_false: false

    - name: Set image target
      id: docker-target
      uses: haya14busa/action-cond@v1
      with:
        cond: ${{ inputs.target != '' }}
        if_true: ${{ inputs.target }}
        if_false: ${{ inputs.image-name }}

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ inputs.image-name }}

    - name: Configure AWS credentials
      if: steps.aws-login.outputs.value == true
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws-access-key }}
        aws-secret-access-key: ${{ inputs.aws-access-secret }}
        aws-region: ${{ inputs.aws-region }}

    - name: Login to Amazon ECR
      if: steps.aws-login.outputs.value == true
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Set image tag
      id: set-tag
      uses: haya14busa/action-cond@v1
      with:
        cond: ${{ steps.aws-login.outputs.value == true }}
        if_true: ${{ steps.login-ecr.outputs.registry }}/${{ steps.meta.outputs.tags }}
        if_false: ${{ inputs.image-name }}

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # - name: Build docker image
    #   id: build-push
    #   uses: docker/build-push-action@v2
    #   with:
    #     context: .
    #     file: Dockerfile
    #     push: ${{ inputs.push }}
    #     load: ${{ inputs.load }}
    #     tags: ${{ steps.set-tag.outputs.value }}
    #     cache-from: |
    #       ${{ inputs.cache-from }}
    #     cache-to: |
    #       ${{ inputs.cache-to }}
    #     target: ${{ inputs.target }}
